# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Checkpoint control plane shared by every Gym server.

Partial rollout checkpointing pauses, drains, commits, and restores Gym
servers in lockstep with the NeMo-RL training checkpoint. The pieces in this
package are the server-side mechanisms that make those control calls safe:

- ``control``: the ``/ng-control/v1`` capability declaration, checkpoint-id
  fencing, phase machine, and deadline plumbing every control route uses.
- ``admission``: the admission limiter that drains a server's data plane to
  a quiescent point and refuses work that can safely be re-issued.
- ``coordinator``: the service-level coordinator that closes every worker's
  limiter and aggregates worker acknowledgements and in-flight counts.
"""

from nemo_gym._checkpoint.admission import (
    GATED_MODEL_ROUTE_SUFFIXES,
    PLANE_HEADER,
    AdmissionLimiter,
    AdmissionMiddleware,
    AdmissionParkedError,
    AdmissionTicket,
    StaleAttemptError,
    bind_current_model_call,
    current_admission_ticket,
    mark_current_generation_safe,
    mark_current_generation_started,
)
from nemo_gym._checkpoint.agent import (
    AGENT_BOUNDARY_SCHEMA_VERSION,
    AGENT_CHECKPOINT_SCHEMA_VERSION,
    AGENT_CHECKPOINT_URL_PREFIX,
    AGENT_CONTINUATION_INDEX_NAME,
    AGENT_EXECUTION_GENERATION_HEADER,
    AGENT_MANIFEST_NAME,
    AGENT_RECORD_INDEX_NAME,
    AGENT_STATE_MANIFEST_SCHEMA_VERSION,
    AGENT_STATE_SUBDIR,
    COMPLETED_RESULT_ACKNOWLEDGEMENT_FEATURE,
    DISCARD_RESTORED_CONTINUATION_FEATURE,
    AgentAcknowledgeRequest,
    AgentAdmissionClosedError,
    AgentBoundaryKind,
    AgentBoundaryRecord,
    AgentCheckpointError,
    AgentCheckpointParticipant,
    AgentCompletedExecutionAcknowledgementError,
    AgentCompletedExecutionAcknowledgementRequest,
    AgentCompletedExecutionAcknowledgementResponse,
    AgentCompletionReceipt,
    AgentDiscardRestoredContinuationRequest,
    AgentExecutionIdentity,
    AgentExecutionState,
    AgentPrepareIncompleteError,
    AgentStaleAttemptError,
    DuplicateExecutionError,
    PendingModelPayload,
    commit_agent_state,
    install_agent_checkpoint,
    restore_agent_state,
)
from nemo_gym._checkpoint.artifacts import (
    AGENT_CONTINUATION_INDEX_FEATURE,
    AGENT_RESOURCE_DEPENDENCY_INDEX_FEATURE,
    CHECKPOINT_ARTIFACT_SCHEMA_VERSION,
    EXTERNAL_STORAGE_REFERENCE_INDEX_FEATURE,
    GENERATION_CUT_LINEAGE_FEATURE,
    AgentContinuationRoot,
    CheckpointArtifactError,
    CheckpointArtifactReference,
    ExternalStorageReference,
    read_jsonl_artifact,
)
from nemo_gym._checkpoint.control import (
    CHECKPOINT_CONTROL_TOKEN_ENV,
    CONTROL_SCHEMA_VERSION,
    CONTROL_URL_PREFIX,
    AdmissionState,
    CheckpointConflictError,
    CheckpointControlRequest,
    CheckpointPhase,
    ControlCapabilities,
    ControlError,
    ControlFence,
    Deadline,
    InvalidPhaseError,
    MultiProcessCapability,
    StaleCheckpointError,
    checkpoint_control_auth_token,
    install_control_plane,
    multi_process_capability_from_num_workers,
)
from nemo_gym._checkpoint.coordinator import (
    AdmissionCoordinator,
    MissingWorkersError,
    WorkerAdmissionAgent,
    WorkerRegistrationError,
    build_coordinator_control_app,
)
from nemo_gym._checkpoint.ledger import (
    LEDGER_MANIFEST_NAME,
    MODEL_CHECKPOINT_URL_PREFIX,
    MODEL_LEDGER_SUBDIR,
    AttemptIdentity,
    CaptureLedgerCheckpointer,
    CaptureLedgerCommitResult,
    CaptureLedgerRestoreResult,
    CheckpointableCaptureLedger,
    LedgerMismatchError,
    LedgerNotCheckpointableError,
    LedgerNotQuiescentError,
    install_model_checkpoint,
)
from nemo_gym._checkpoint.model_admission import (
    NotPolicyInstanceError,
    install_model_admission,
)
from nemo_gym._checkpoint.model_control_contracts import (
    MODEL_ADMISSION_URL_PREFIX,
    GenerationCutAck,
    GenerationCutBackend,
    GenerationCutCoordinatorProof,
    GenerationCutFrozenTicket,
    GenerationCutInventory,
    GenerationCutLineageRecord,
    GenerationCutPrefix,
    GenerationCutPrefixAck,
    GenerationCutReceipt,
    GenerationCutReplacement,
    GenerationCutWorkerProof,
    ModelAbortInflightRequest,
    ModelAdmissionPauseRequest,
    ModelAdmissionResumeRequest,
)
from nemo_gym._checkpoint.resources import (
    EXPECTED_RESOURCE_STATE_REVISION_HEADER,
    RESOURCE_REQUEST_ID_HEADER,
    RESOURCE_STATE_REVISION_HEADER,
    RESOURCES_CHECKPOINT_SCHEMA_VERSION,
    RESOURCES_CHECKPOINT_URL_PREFIX,
    RESOURCES_MANIFEST_NAME,
    RESOURCES_STATE_SUBDIR,
    ResourceMutationReceipt,
    ResourceReceiptCapacityError,
    ResourceReceiptEvictedError,
    ResourceRequestReceiptError,
    ResourceRevisionMismatchError,
    ResourcesAdmissionClosedError,
    ResourcesCheckpointError,
    ResourcesCheckpointParticipant,
    ResourceSnapshot,
    ResourcesRetireRequest,
    ResourcesRouteKind,
    ResourcesSessionMiddleware,
    ResourcesSessionUnboundError,
    ResourcesStaleAttemptError,
    ResourcesUncertainMutationError,
    ResourcesUnsafeRestoreError,
    commit_resources_state,
    install_resources_checkpoint,
    load_resources_state,
)


__all__ = [
    "AGENT_BOUNDARY_SCHEMA_VERSION",
    "AGENT_CHECKPOINT_SCHEMA_VERSION",
    "AGENT_CHECKPOINT_URL_PREFIX",
    "AGENT_CONTINUATION_INDEX_NAME",
    "AGENT_CONTINUATION_INDEX_FEATURE",
    "AGENT_RESOURCE_DEPENDENCY_INDEX_FEATURE",
    "AGENT_EXECUTION_GENERATION_HEADER",
    "AGENT_MANIFEST_NAME",
    "AGENT_RECORD_INDEX_NAME",
    "AGENT_STATE_SUBDIR",
    "AGENT_STATE_MANIFEST_SCHEMA_VERSION",
    "COMPLETED_RESULT_ACKNOWLEDGEMENT_FEATURE",
    "CHECKPOINT_ARTIFACT_SCHEMA_VERSION",
    "CONTROL_SCHEMA_VERSION",
    "CONTROL_URL_PREFIX",
    "CHECKPOINT_CONTROL_TOKEN_ENV",
    "EXPECTED_RESOURCE_STATE_REVISION_HEADER",
    "GATED_MODEL_ROUTE_SUFFIXES",
    "LEDGER_MANIFEST_NAME",
    "MODEL_ADMISSION_URL_PREFIX",
    "MODEL_CHECKPOINT_URL_PREFIX",
    "MODEL_LEDGER_SUBDIR",
    "PLANE_HEADER",
    "RESOURCES_CHECKPOINT_SCHEMA_VERSION",
    "RESOURCES_CHECKPOINT_URL_PREFIX",
    "RESOURCES_MANIFEST_NAME",
    "RESOURCES_STATE_SUBDIR",
    "RESOURCE_REQUEST_ID_HEADER",
    "RESOURCE_STATE_REVISION_HEADER",
    "AdmissionLimiter",
    "AdmissionMiddleware",
    "AdmissionCoordinator",
    "AdmissionParkedError",
    "AdmissionState",
    "AdmissionTicket",
    "GenerationCutAck",
    "GenerationCutBackend",
    "GenerationCutCoordinatorProof",
    "GenerationCutFrozenTicket",
    "GenerationCutInventory",
    "GenerationCutLineageRecord",
    "GenerationCutPrefix",
    "GenerationCutPrefixAck",
    "GenerationCutReplacement",
    "GenerationCutReceipt",
    "GenerationCutWorkerProof",
    "AgentAdmissionClosedError",
    "AgentAcknowledgeRequest",
    "AgentContinuationRoot",
    "AgentBoundaryKind",
    "AgentBoundaryRecord",
    "AgentCheckpointError",
    "AgentCheckpointParticipant",
    "AgentCompletionReceipt",
    "AgentCompletedExecutionAcknowledgementError",
    "AgentCompletedExecutionAcknowledgementRequest",
    "AgentCompletedExecutionAcknowledgementResponse",
    "AgentExecutionIdentity",
    "AgentExecutionState",
    "AgentPrepareIncompleteError",
    "AgentStaleAttemptError",
    "MissingWorkersError",
    "ModelAbortInflightRequest",
    "ModelAdmissionPauseRequest",
    "ModelAdmissionResumeRequest",
    "WorkerAdmissionAgent",
    "WorkerRegistrationError",
    "build_coordinator_control_app",
    "bind_current_model_call",
    "commit_agent_state",
    "commit_resources_state",
    "checkpoint_control_auth_token",
    "current_admission_ticket",
    "CheckpointConflictError",
    "CheckpointArtifactError",
    "CheckpointArtifactReference",
    "CheckpointControlRequest",
    "CheckpointPhase",
    "ControlCapabilities",
    "ControlError",
    "ControlFence",
    "Deadline",
    "DuplicateExecutionError",
    "ExternalStorageReference",
    "EXTERNAL_STORAGE_REFERENCE_INDEX_FEATURE",
    "GENERATION_CUT_LINEAGE_FEATURE",
    "AttemptIdentity",
    "CaptureLedgerCommitResult",
    "CaptureLedgerCheckpointer",
    "CaptureLedgerRestoreResult",
    "CheckpointableCaptureLedger",
    "InvalidPhaseError",
    "LedgerMismatchError",
    "LedgerNotCheckpointableError",
    "LedgerNotQuiescentError",
    "MultiProcessCapability",
    "NotPolicyInstanceError",
    "PendingModelPayload",
    "ResourceSnapshot",
    "ResourceMutationReceipt",
    "ResourceReceiptCapacityError",
    "ResourceReceiptEvictedError",
    "ResourceRequestReceiptError",
    "ResourceRevisionMismatchError",
    "ResourcesAdmissionClosedError",
    "ResourcesCheckpointError",
    "ResourcesCheckpointParticipant",
    "ResourcesRetireRequest",
    "ResourcesRouteKind",
    "ResourcesSessionUnboundError",
    "ResourcesSessionMiddleware",
    "ResourcesStaleAttemptError",
    "ResourcesUncertainMutationError",
    "ResourcesUnsafeRestoreError",
    "StaleAttemptError",
    "StaleCheckpointError",
    "install_agent_checkpoint",
    "install_control_plane",
    "install_model_admission",
    "install_model_checkpoint",
    "install_resources_checkpoint",
    "load_resources_state",
    "multi_process_capability_from_num_workers",
    "mark_current_generation_safe",
    "mark_current_generation_started",
    "restore_agent_state",
    "read_jsonl_artifact",
]
